name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]

    runs-on: ${{ matrix.os }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
